app:
  upload-dir: ${upload-dir}
  # console-log-charset: ${console-log-charset}

spring:
  config:
    activate:
      on-profile: "dev"
  datasource:
    # driver-class-name: org.h2.Driver
    # url: jdbc:h2:mem:dev
    # username: sa
    # password:
    # driver-class-name: oracle.jdbc.driver.OracleDriver
    # url: jdbc:log4jdbc:oracle:thin:@10.10.1.2:1521/xepdb1
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@localhost:1120/xe
    # url: jdbc:oracle:thin:@localhost:1120/xe
    username: oa
    password: oa
  # oa:
  #   datasource:
  #     driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  #     url: jdbc:log4jdbc:oracle:thin:@localhost:1120/xe
  #     username: OA
  #     password: OA
  # oahd:
  #   datasource:
  #     driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  #     url: jdbc:log4jdbc:oracle:thin:@localhost:1120/xe
  #     username: OAHD
  #     password: OAHD
  # oasi:
  #   datasource:
  #     driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  #     url: jdbc:log4jdbc:oracle:thin:@localhost:1120/xe
  #     username: OASI
  #     password: OASI
  
  jpa:
    # database: h2
    # database-platform: org.hibernate.dialect.H2Dialect
    database: oracle
    database-platform: org.hibernate.dialect.Oracle12cDialect
    show-sql: true
    # generate-ddl: true
    # defer-datasource-initialization: true
    # hibernate:
      # none validate create create-drop update
      # ddl-auto: create-drop
    properties:
      hibernate:
        format-sql: true
        # dialect: org.hibernate.dialect.H2Dialect
        # dialect: org.hibernate.dialect.Oracle12cDialect
  # sql:
  #   init:
  #     mode: never
  # h2:
  #   console:
  #     enabled: true

# logging:
#   charset:
#     # 윈도우의 콘솔 로그에서 한글 깨지는 문제로 삽입 - UTF-8(x), MS949(o)
#     console: ${app.console-log-charset}